In [2]:
import numpy as np
import numpy.random as random
import scipy as sp
from pandas import Series, DataFrame
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

import sklearn

%precision 3

'%.3f'

In [ ]:
import requests, zipfile
import io
import pandas as pd

# Corrected URL
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
res = requests.get(url).content

# Use comma as the delimiter (the data is comma-separated)
auto = pd.read_csv(io.StringIO(res.decode('utf-8')), header=None, sep=',')

auto.columns = ['symboling', 'normalized-losses','make','fuel-type','aspiration','num-of-doors',
                'body-style','drive-wheels','engine-location','wheel-base','length','width','height',
                'curb-weight','engine-type','num-of-cylinders','engine-size','fuel-system','bore',
                'stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg','price']

print('自動車データの形式 : {}'.format(auto.shape))

auto.head()

自動車データの形式 : (205, 26)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
auto = auto[['price','horsepower','width','height']]
auto.isin(['?']).sum()

price         4
horsepower    2
width         0
height        0
dtype: int64

In [ ]:
auto = auto.replace('?', np.nan).dropna()
print('自動車データの形式 : {}'.format(auto.shape))

自動車データの形式 : (199, 4)

In [ ]:
print('データの型の確認 (型変換前) \n{}\n'.format(auto.dtypes))

データの型の確認 (型変換前)
price          object
horsepower     object
width         float64
height        float64
dtype: object

In [ ]:
auto = auto.assign(price=pd.to_numeric(auto['price']))
auto = auto.assign(horsepower=pd.to_numeric(auto['horsepower']))
print()
print('データの型の確認 (型変換後) \n{}\n'.format(auto.dtypes))

データの型の確認 (型変換後)
price           int64
horsepower      int64
width         float64
height        float64
dtype: object

In [ ]:
auto.corr()

               price  horsepower     width    height
price       1.000000    0.810533  0.753871  0.134990
horsepower  0.810533    1.000000  0.615315 -0.087407
width       0.753871    0.615315  1.000000  0.309223
height      0.134990   -0.087407  0.309223  1.000000

In [ ]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

x = auto.drop('price', axis=1)
y = auto['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

model = LinearRegression()
model.fit(x_train, y_train)

print('決定係数(train):(:.3f)'.format(model.score(x_train, y_train)))
print('決定係数(test):(:.3f)'.format(model.score(x_test, y_test)))

print('回帰係数 \n{}'.format(pd.Series(model.coef_, index=x.columns)))
print('切片 \n{}'.format(model.intercept_))

決定係数(train):(:.3f)
決定係数(test):(:.3f)
回帰係数
horsepower     121.094372
width         1251.650344
height         282.848038
dtype: float64
切片
-97207.75670162441

In [7]:
# Practice 8-1
import requests, zipfile
import io

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
res = requests.get(url).content

auto = pd.read_csv(io.StringIO(res.decode('utf-8')), header=None, sep=',')
auto.columns = ['symboling', 'normalized-losses','make','fuel-type','aspiration','num-of-doors',
                'body-style','drive-wheels','engine-location','wheel-base','length','width','height',
                'curb-weight','engine-type','num-of-cylinders','engine-size','fuel-system','bore',
                'stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg','price']

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

auto = auto[['price','horsepower','width','height']]
auto = auto.replace('?', np.nan).dropna()

X = auto.drop('price', axis=1)
y = auto['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)

print('決定係数(train):{:.3f}'.format(model.score(X_train, y_train)))
print('決定係数(test):{:.3f}'.format(model.score(X_test, y_test)))

決定係数(train):0.740
決定係数(test):0.799

In [8]:
# Practice 8-2
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

cancer = load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3, random_state=0)

model = LogisticRegression()
model.fit(X_train, y_train)

print('決定係数(train):{:.3f}'.format(model.score(X_train, y_train)))
print('決定係数(test):{:.3f}'.format(model.score(X_test, y_test)))

決定係数(train):0.942
決定係数(test):0.953

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [13]:
# Practice 8-4
from sklearn.linear_model import LinearRegression, Lasso

X = auto.drop('price', axis=1)
y = auto['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

models = {
    'linear': LinearRegression(),
    'lasso1': Lasso(alpha=1.0, random_state=0),
    'lasso2': Lasso(alpha=200.0, random_state=0)
}

score = {}

for model_name, model in models.items():
    model.fit(X_train, y_train)
    score[model_name, 'test'] = model.score(X_test, y_test)
    score[model_name, 'train'] = model.score(X_train, y_train)

pd.Series(score).unstack()

            test     train
lasso1  0.799254  0.739741
lasso2  0.796952  0.739479
linear  0.799265  0.739741

**ラッソとリッジ回帰で用いられる正則化項式のメリット**

係数の縮小：正則化により、全ての係数が少しずつ縮小されることにより、モデルの複雑さが抑えられ、過学習を防ぐ。

安定性の向上：データに対するロバスト性が向上し、データに含まれるノイズや多重共線性がある場合でも、より安定した予測結果が得られる。

モデルの簡素化：不要な変数が削除されるため、より簡素で解釈しやすいモデルが得られる。